coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
