
default:
  protocol: mongodb
  options:
    useMongoClient: true

test: &test
  host: ds157390.mlab.com
  port: 57390
  user: test
  pwd: test
  database: chicking-todo-test

development:
  <<: *test

production:
  host: #{process.env.DB_HOST}
  port: #{process.env.DB_PORT}
  user: #{process.env.DB_USERNAME}
  pwd: #{process.env.DB_PASSWORD}
  database: #{process.env.DB_NAME}
